### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by DericZhao** [ImKeTT/Awesome-Multi-Modal-Dialog#1]
这个paper list很不错，请问还会更新么？

**Comment by ImKeTT** [comment]
谢谢您的关注，但是这个paperlist恐怕不会再更新了。一方面时间有限，另一方面近一年已经出现很多类似而且保持更新的paper list了，例如这个 https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models
